language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
script: python setup.py test
deploy:
  provider: pypi
  user: magland
  on:
    tags: true
env:
  global:
  - secure: QEDJaYBpVX1ERv9U/9Gvp/vmn1N3NQMv/N33u39Lx0hyHbY9BmLsz6z2PylFxhbUWH2AKqTBSKeBD1U67ZY720QtQeJLQVvrQrnk72etxdhoLW7d/L1gnPzl+o3KmMt50cq6nOl1KnhV91fNIMutqWCy9LQQjSWmYlpGOokDBYi1nwJ3gOHoA2MW1M2R+qFJ4mT601JTnzzBrCQeetYj6cLs/93E2AHa2+ymuEs692QpORvtdG5StNmjNya/UnXQbzx/3wPm73ZtlSo68TYMgiBEzdM39EwXz/6mPt6NOAItBPJfLSfh23l1NjfS5UnhutExMhbTpX3FF2sQtDhKd33ARWS7ZhaQd/Oq23ziNc1hyAiw4kamPQfT0Q3weI2hQmhrPtLx2nBiMuxe4M61TDjR1eFx0l6FP5vj4XkB1DKRDEH+8MdVzzoheO9mhCvFUfaDK8CSytOoMIQqGqIXiCBv0rw0GxjJ7Hw2JdLM95Wni0seYU2x/VZpX9yqgFc8aWtwiCoJz5MKExinChmMjXSqpkTL/ABD5Z+KWDtwIL4EjqrLQ+0MXHqzLPynoq2NVA7jqA4SYzQqcoKSaZSaZ47UfWkMEb1I1t30rd7gOOfx1a5QDGTQRugGwWP0Uy1oThNpPIVqNbLehuj8ei3kNMmeTMTid3imfMg1WPWhzHc=
  - secure: PPQC3cQndsn4EWUrth+PzxFdoECW1nJawXSeFvMldJtAPYErlixZB99uGXBtCRMR+rOll7Dk9BEaGgTXVTUWVN/ZiEGWxcfWR2e/8okeT4x1+d10z/tsXxgRcqDykHRidbvLCtq8nYTRu6d8JXHIBB68wFB0fbUX59G4UF/jabdXnAS8YXMtUHJCqkXvXDiPuETUCEsTl3hMe93IdKEvWaFZgtK2ZTWaBnfIc0CrHHcfIsUOLNDziO4Y2UORGR4/qNXHDY+UaLatjFggzMkb7sjzkzv+A9eSGBGqbqE8lEoPc3gNTZtxVkEwwBjaaBcRxtAkRwEZ7hPtS6IDGiIKyM4TUEE0DHTAg3vfA4DzXMGlAyeNtoQHTHiDSeAZ9hlfq4KRQEhri+Pm6ZWoyon79wlphMaNtvj3spDVo0VT2n3eY/iks5Txi/AICjvOFMTd9KfjJtfa3XNVgMXlM6rV36N9/LGiGJCmoM2o8FwffWnM/zBi+1AR0DBlRU+RqseaqQjcjbvPXfcp4innPWdk4r7P5dt6I+NBhwQbWpjs6Ci2UINFUrWLriA1xxLh/645YcE6sFXiNhq+GTzy6Fy6yXzzR6WmQUDUZA7ddXjUF48a/HMZ9NRhv3X/HxWG+wIywkIiejlUcx224x72ectL7lQ64DL5VpngR4E0vqL4Owg=
