language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
- pip install pytest
script: pytest
deploy:
  provider: pypi
  user: magland
  on:
    tags: true
  password:
    secure: nDC4cYKvwM3d6Tvznf5zNisdFKSpbVRsax70F4aEBc/+D+S9Ylryz/gv4fdIUhcSk56A6Ai2gtSgPRBwKaYNhs1JKAhnuTGPHeX4IyJlgvYviYRlTv9hsTqgnHeI+52MdCtz7EFWxhvl5eA8GdXcoXC0THY85iQXeieekwpPdlSMSVDfDkj3RT4REffUNTv/ffGG9VXOSGmgU+tUjLtrAMBrM8h1BVVrS3j76HUNS49vP1RbqHQNClL11nAFJDeiGVtYp1+F+RZheFIZayGu/UQQqRxIBg9mHqw3r9qBHf110sN4/j1DgMPIbsPX1be+Y0UMC3OXbZ3KorjcDTHfZOM1odmdh4zwqPEOEJhs2O4M2HKByRRUE7ee+PAqArwBL/endaAwjMIYgA1qb/M1hg2p2Gtq3rufnMi0quCCMqqllnWyo2a2Lfp0Ak+oiXjX0xKifhE9NFcCsQ9Rgtt1btlxkJ2dUVXDkm7KGQgdJbAFfLWVWWsWfjuEYnMlj+qah88k8vfRgY23c3pnKekGdewmm0KZxU8SypMlq3nz/PICQysX62CITJ+D4wTaKvPzAAd4M8dxn3xNydfwsjaMYZTx1yw+hJqI6ewPqF6ivRiBtIEDk1GT1+MCYHZSvjArd266Uz/tUZlTnCto8oNgj4EyKeHrYd0SIACQHEjf9f0=
