language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
- pip install pytest
script: pytest
deploy:
  provider: pypi
  user: magland
  on:
    tags: true
  password:
    secure: hroq72Sy4NTTKRZPy9RB7nzejYzIXmYRzpzpCKXDFzw6TJ8e96ajIl5I/GyrRJM15GN1fBdKTfYFp2ITV1wN98bf/Wuqasr4et7bNxENAXrCOq9xRyaNJiHiKBzdlKN1HkvFF1xGhm8EIXiP4G6fG8CPDKwb/dBsLPgJdsyOmX88QCq07SgyoGA+X69IoIIhapjWS32SJycfkif6WtoHBrlHGkl1BjfPqOR1nxcztVwn0AqLGeCWYrHePVLINcYYf8gCVx5J2BeoG/0mOGsrRrVyi8l1+r7mbfJyCBUPdrsrQihiA0auZrJplExtlWb1iwSJ5PmMi3dpC3T1TXXWyS1Npaz97dmlSFj7Jd0FlU02TibYjGQFUfDLjMlKPmLZNHk5Ylh4/tuj3l8yQP171qD8ZQ2ed/zxUyhGQaZBgZovzJsQbHSmYvARrrSQyWTjUDNR0VttrmPZdf0V2x1FBCso9EAJOy6xCjpeUlla2D9U268IYYY1XO9RmTWeaAeZ32QCkO4R6dPTOoJ8RyBhWJ+2Fv1gv8U1tIcC2sj1vv+MqadGZBA7MUI5hO5qhPYkBKfAGy8E045tCR/zUKxWdad5wdA9To2OWucvQwvcvLKepq2oqOHls9KGixYSwGi2lXpNTvyEPxC+kSxo9q+7EtDGchXGdssvDv9j0tXaq8Q=
