language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
script: python setup.py test
deploy:
  provider: pypi
  user: magland
  on:
    tags: true
  password:
    secure: GQS5dFvdkAPM0KSZEKgPd2jwA8B2PYlAFVsxwgw+wLpWaXe07MuAe4m4O6fRZlgF7rBpuHqxzdeKD9UxjHo2171h4RcTe82d3hEukkLx7FdhJarztd8kVr7WksdjO34GJghAA0fh1+vqGsuwqeA1jtN+g5Yqy5oRqe1qE9dPYkVUJhnZBazAsCEWqCIa00pX9QXNRjDXZKE7/+0cg/r5fQEK4Ad0xHdpdoNXWz2JokQrbvBN4vP2ghE7VkmQv9tDAZfWeM8vcYVhANxmLq/sOBBgzJ16DA3WihWt09Joyq4ZppBpN3nJLd67VSb4k08dBSU8flb9Ojd4TXMYfX8DyP4iTt0OzoUCT1hc6fmcd1pBcPE1iXyjamdTtUcqXCLPsNx1JBpaj6irMFTKnlclu+lgX5BTlqOx56RcmklUNdwM3W/0OGY3Jc3esxo4Roeh7BYspD8QEHTOKkmQ1M8KMa5WTmPpqq3Kynf1vuLZg/4Hjs90xg2daGhwDs2OxTTkUL/NcLU+GPHFlxYtPQRNa3GWsuFho+XRUpiF1cni0Ht3se4YlnkJfwVARcJu/RwyguJpilzgN0On4XuM3rLSpKaN/+Ro5RTN9LEk8xpTX5zRILUk6KGUJkDqIxgqic9JdJZ5khm54cwYmLZf6UFvlXUPBT5Q/G6oRcASQuJgpsA=
