language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install https://github.com/SpikeInterface/spikeextractors/archive/master.zip
- pip install https://github.com/SpikeInterface/spiketoolkit/archive/master.zip
- pip install https://github.com/SpikeInterface/spikecomparison/archive/master.zip
- pip install requests
- pip install networkx
- pip install matplotlib
- pip install .
- pip install pytest
script: pytest
deploy:
  provider: pypi
  user: alejoe91
  on:
    tags: true
  password:
    secure: GFw2eDDce8QumrMJO9wV3ZkIUQwbCC59sOXsByW4kQggvKaVuW1zYhE++BlU9ZpIxJbHfbtBNv/JFr6AU7rhc4QPTiRZpLeAf5rY3Nrpz0pG/E/Lms8+tCDbOmDc9ERH09jISy6q5VN6JV9li7NFldEM9jJJgr0AjSkLIxBFyAynkcVFpu3sRpubej1velWRdeKMOnFZZjWLMfS1/KCeRAP7V9K0wQD+t3YdauXZBBUq9U75QmF6kttiDkp4AApOXajtF0Hg0pSjj0futa2OBIT//3zdvUxNo4mQRLpqmv/lC9CHNfJwlam9ZAv9UKXfSxMrCuoH/iA/s3vvh881XXJ2BgQz6iaYi9OZh7PKnIASM8EQYqzDHNwfbL3tpnJYsyw+98Qc6l5gK+jZwjerv92Sb+E7elVhNPWnAhXbjz5xoLQgd8pKJHa2B9cwIWa9RMFZmbjQ7fmd9taEtnkcyo/fysFJJKXBzeZlREQ5v8L/NJv21mxaBdqMqqWDPrMYv/cXlgEbKPBHtXoPtie/73qs5EPUtjQszFAiZbBBIm2uvY5I+YX7CsEm021JJhFzkpjBqqXKVGyHnazJS+Q2PT0poQfFNK/1aigs4+MZGQ52ERnIZskXt2PoCrk76afjxfGQ2TS6wyVwZJddP95PR035lKmRrpYtKbIfzf/WL9I=
